// Add steps as necessary for accessing the software, post-configuration, and testing. Don’t include full usage instructions for your software, but add links to your product documentation for that information.
//Should any sections not be applicable, remove them

== Test the deployment

Once installed, you can verify that everything is working with the following command:

```
kubectl get tigerastatus
```

A successful installation will indicate a status of "Available", with "Degraded" and "Progressing" marked as "False".

For example:

```
NAME     AVAILABLE   PROGRESSING   DEGRADED   SINCE
calico   True        False         False      1m16s
```

== Post deployment steps

You're now ready to use {partner-product-name}! To begin using the software, follow this guide to https://docs.projectcalico.org/security/kubernetes-network-policy[get started with Kubernetes network policy^].

To enable additional {partner-product-name} Enterprise features, see the https://www.tigera.io/tigera-products/calico-enterprise/?utm_campaign=eksquickstart&utm_medium=web&utm_source=aws[Tigera documentation^].

== Other useful information

Useful references for getting started with {partner-product-name}:

- https://docs.projectcalico.org/security/adopt-zero-trust[Adopt a zero-trust network model for security^]
- https://docs.projectcalico.org/security/kubernetes-network-policy[Get started with Kubernetes network policy^]
- https://docs.projectcalico.org/security/calico-network-policy[Get started with {partner-product-name} network policy^]
